
path: ../dataset/dataset_v20250506/ # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: ashore
  1: above
  2: under
